# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Designs\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(640, 480))
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.nameBeforeIndex = QtWidgets.QLineEdit(self.centralwidget)
        self.nameBeforeIndex.setObjectName("nameBeforeIndex")
        self.horizontalLayout_2.addWidget(self.nameBeforeIndex)
        self.indexSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.indexSpinBox.setProperty("value", 1)
        self.indexSpinBox.setObjectName("indexSpinBox")
        self.horizontalLayout_2.addWidget(self.indexSpinBox)
        self.nameAfterIndex = QtWidgets.QLineEdit(self.centralwidget)
        self.nameAfterIndex.setObjectName("nameAfterIndex")
        self.horizontalLayout_2.addWidget(self.nameAfterIndex)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setMovement(QtWidgets.QListView.Static)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.renameButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.renameButton.setFont(font)
        self.renameButton.setObjectName("renameButton")
        self.horizontalLayout.addWidget(self.renameButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.openFilesAction = QtWidgets.QAction(MainWindow)
        self.openFilesAction.setObjectName("openFilesAction")
        self.rotateListAction = QtWidgets.QAction(MainWindow)
        self.rotateListAction.setObjectName("rotateListAction")
        self.menu.addAction(self.openFilesAction)
        self.menu.addAction(self.rotateListAction)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Renamer"))
        self.label.setText(_translate("MainWindow", "Новое название:"))
        self.listWidget.setSortingEnabled(False)
        self.renameButton.setText(_translate("MainWindow", "Переименовать"))
        self.menu.setTitle(_translate("MainWindow", "Файлы"))
        self.openFilesAction.setText(_translate("MainWindow", "Открыть файлы"))
        self.rotateListAction.setText(_translate("MainWindow", "Развернуть список файлов"))
